name: eShopOnWeb Build and Test

#Triggers (uncomment line below to use it)
on: [push, workflow_dispatch]

#Environment variables https://docs.github.com/en/actions/learn-github-actions/environment-variables
env:
  RESOURCE-GROUP: RG-eshoponweb-name
  LOCATION: eastus
  TEMPLATE-FILE: infra/webapp.bicep
  SUBSCRIPTION-ID: b0bd70b6-22ec-4849-be86-a1f784bb8d93
  WEBAPP-NAME: eshoponweb-webapp-NAME-spsk

jobs:
  #Build, test and publish .net web project in repository
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      #checkout the repository
      - uses: actions/checkout@v5
      #prepare runner for desired .net version SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"
          dotnet-quality: "preview"
      #Build/Test/Publish the .net project
      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release
      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release
      
      # 1. Create the Zipped Artifact
      - name: Create Web App Deployment Zip
        run: |
          # Publish the project to a local folder named 'app-output'
          dotnet publish ./src/Web/Web.csproj -c Release -o ./app-output
          
          # Zip the contents of 'app-output' directly into a file named 'web.zip'
          zip -r web.zip ./app-output
          
          # Verify the zip file was created. Failure here will stop the workflow.
          ls -l web.zip
          
      # 2. Upload Artifact: .net-app
      - name: Upload .net-app Artifact
        uses: actions/upload-artifact@v5
        with:
          name: .net-app
          path: web.zip 

      # 3. Upload Artifact: bicep-template
      - name: Upload bicep-template Artifact
        uses: actions/upload-artifact@v5
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE-FILE }} 

  # Use Bicep to deploy infrastructure + Publish webapp
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: "Development"
    steps:
      #Download the publish files created in previous job
      - name: Download artifact from build job
        uses: actions/download-artifact@v6
        with:
          name: .net-app
          path: .net-app

      #Download the bicep templates from previous job
      - name: Download artifact from build job
        uses: actions/download-artifact@v6
        with:
          name: bicep-template
          path: bicep-template

      #Login in your azure subscription using a service principal (credentials stored as GitHub Secret in repo)
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Azure WebApp using Bicep file
      - name: deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: bicep-template/webapp.bicep
          parameters: "webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}"
          failOnStdErr: false

      # Publish website to Azure App Service (WebApp)
      # Step disabled due to issue where the site sometimes can't be found: https://github.com/microsoft/pipelines-appservice-lib/issues/56. Instead deploy using CLI
      - name: Publish Website to WebApp
        if: false #Disable step due to comment above
        uses: Azure/webapps-deploy@v3
        with:
          type: ZIP
          app-name: ${{ env.WEBAPP-NAME  }}
          package: .net-app/app.zip

      # Publish website to Azure App Service using CLI (WebApp)
      - name: Publish Website to WebApp
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy --name ${{ env.WEBAPP-NAME }} --resource-group ${{ env.RESOURCE-GROUP }} --src-path .net-app/app.zip --type zip
